import { Keybind } from './src'

const custom: Keybind[] = [
    { command: '-workbench.action.terminal.runRecentCommand', key: '^+alt+r', when: 'terminalFocus && terminalHasBeenCreated && !accessibilityModeEnabled || terminalFocus && terminalProcessSupported && !accessibilityModeEnabled' },
    { command: '-workbench.view.debug', key: '^+shift+d', when: 'viewContainer.workbench.view.debug.enabled' },
    { command: '-inlineChat.quickVoice.start', key: '^+k i', when: 'editorFocus && hasSpeechProvider && !inlineChat.quickChatInProgress' },
    { command: '-inlineChat.quickVoice.stop', key: '^+k i', when: 'hasSpeechProvider && inlineChat.quickChatInProgress' },
    { command: '-workbench.action.copyEditorToNewWindow', key: '^+k o', when: 'activeEditor' },
    { command: '-workbench.action.showTreeHover', key: '^+k ^+i', when: 'customTreeView && listFocus && !inputFocus && !treestickyScrollFocused' },
    { command: 'editor.emmet.action.evaluateMathExpression', key: '^+m' },
    { command: '-editor.action.clipboardPasteAction', key: 'shift+insert' },
    { command: '-notebook.cell.paste', key: 'v', when: 'notebookEditorFocused && !inputFocus && !notebookOutputInputFocused' },
    { command: '-editor.action.insertSnippet', key: '^+alt+j', when: "editorTextFocus && !editorReadonly && editorLangId == 'nushell'" },
    { command: '-inlineChat.start', key: '^+i', when: 'inlineChatHasProvider && !editorReadonly' },
    { command: '-editor.action.triggerSuggest', key: '^+i', when: 'editorHasCompletionItemProvider && textInputFocus && !editorReadonly && !suggestWidgetVisible' },
    { command: '-markdown.extension.editing.toggleItalic', key: '^+i', when: 'editorTextFocus && !editorReadonly && editorLangId =~ /^markdown$|^rmd$|^quarto$/' },
    { command: '-toggleSuggestionDetails', key: '^+i', when: 'suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && textInputFocus' },
    { command: '-focusSuggestion', key: '^+i', when: 'suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion' },
    { command: '-github.copilot.terminal.suggestCommand', key: '^+i', when: 'terminalFocus' },
    { command: '-workbench.action.tasks.build', key: '^+shift+b', when: 'taskCommandsRegistered' },
    { command: '-editor.action.selectHighlights', key: '^+shift+l', when: 'editorFocus' },
    { command: '-workbench.view.debug', key: '^+shift+d', when: 'viewContainer.workbench.view.debug.enabled' },
    { command: '-workbench.action.focusFirstEditorGroup', key: '^+1' },
    { command: '-workbench.view.explorer', key: '^+shift+e', when: 'viewContainer.workbench.view.explorer.enabled' },
    { command: '-workbench.view.scm', key: '^+shift+g', when: 'workbench.scm.active' },
    { command: '-workbench.action.focusSecondEditorGroup', key: '^+2' },
    { command: '-workbench.action.focusThirdEditorGroup', key: '^+3' },
    { command: '-editor.action.copyLinesDownAction', key: 'shift+alt+down', when: 'editorTextFocus && !editorReadonly' },
    { command: '-notebook.cell.copyDown', key: 'shift+alt+down', when: 'notebookEditorFocused && !inputFocus' },
    { command: '-markdown.extension.onCopyLineDown', key: 'shift+alt+down', when: 'editorTextFocus && !editorReadonly && !suggestWidgetVisible && editorLangId =~ /^markdown$|^rmd$|^quarto$/\n' },
    { command: '-editor.action.copyLinesUpAction', key: 'shift+alt+up', when: 'editorTextFocus && !editorReadonly' },
    { command: '-notebook.cell.copyUp', key: 'shift+alt+up', when: 'notebookEditorFocused && !inputFocus' },
    { command: '-markdown.extension.onCopyLineUp', key: 'shift+alt+up', when: 'editorTextFocus && !editorReadonly && !suggestWidgetVisible && editorLangId =~ /^markdown$|^rmd$|^quarto$/\n' },
    { command: '-editor.action.insertCursorAtEndOfEachLineSelected', key: 'shift+alt+i', when: 'editorTextFocus' },
    { command: '-editor.action.addCommentLine', key: '^+k ^+c', when: 'editorTextFocus && !editorReadonly' },
    { command: '-workbench.action.debug.restart', key: '^+shift+f5', when: 'inDebugMode' },
    { command: '-workbench.action.previousEditorInGroup', key: '^+k ^+pageup' },
    { command: '-workbench.action.nextEditorInGroup', key: '^+k ^+pagedown' },
    { command: '-editor.action.jumpToBracket', key: '^+shift+oem_5', when: 'editorTextFocus' },
    { command: '-workbench.action.toggleSidebarVisibility', key: '^+b' },
    { command: '-editor.action.organizeImports', key: 'shift+alt+o', when: 'textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)source\\.organizeImports\\b/' },
    { command: '-workbench.action.files.openFile', key: '^+o', when: 'true' },
    { command: '-workbench.action.files.openFolderViaWorkspace', key: '^+o', when: "!openFolderWorkspaceSupport && workbenchState == 'workspace'" },
    { command: '-workbench.action.files.openFileFolder', key: '^+o', when: 'isMacNative && openFolderWorkspaceSupport' },
    { command: '-workbench.action.files.openLocalFile', key: '^+o', when: 'remoteFileDialogVisible' },
    { command: '-workbench.action.openSettings', key: '^+oem_comma' },
    { command: '-workbench.action.files.saveAs', key: '^+shift+s' },
    { command: '-workbench.action.files.saveLocalFile', key: '^+shift+s', when: 'remoteFileDialogVisible' },
    { command: '-saveAll', key: '^+k s' },
    { command: '-workbench.action.files.saveWithoutFormatting', key: '^+k ^+shift+s' },
    { command: '-markdown.extension.editing.toggleStrikethrough', key: 'alt+s', when: 'editorTextFocus && !editorReadonly && editorLangId =~ /^markdown$|^rmd$|^quarto$/' },
    { command: '-workbench.action.chat.insertCodeBlock', key: '^+enter', when: 'accessibilityModeEnabled && hasChatProvider && inChat' },
    { command: '-github.copilot.generate', key: '^+enter', when: 'editorTextFocus && github.copilot.activated && !inInteractiveInput && !interactiveEditorFocused' },
    {
        command: '-extension.node-debug.startWithStopOnEntry',
        key: 'f11',
        when: "!inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'node' || !inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'pwa-extensionHost' || !inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'pwa-node'\n",
    },
    { command: '-workbench.action.debug.stepInto', key: 'f11', when: "debugState != 'inactive'" },
    { command: '-workbench.action.toggleFullScreen', key: 'f11', when: '!isIOS' },
    { command: '-workbench.action.toggleZenMode', key: '^+k z' },
    { command: '-jupyter.runcurrentcell', key: '^+enter', when: 'editorTextFocus && isWorkspaceTrusted && jupyter.hascodecells && !editorHasSelection && !jupyter.havenativecells && !notebookEditorFocused\n' },
    { command: '-jupyter.runByLineStop', key: '^+enter', when: "notebookCellResource in 'jupyter.notebookeditor.runByLineCells'" },
    { command: '-notebook.cell.executeAndFocusContainer', key: '^+enter', when: 'notebookCellListFocused || editorTextFocus && inputFocus && notebookEditorFocused' },
    { command: '-notebook.cell.insertCodeCellBelow', key: '^+enter', when: 'notebookCellListFocused && !inputFocus' },
    { command: '-workbench.action.quickOpenNavigatePreviousInFilePicker', key: '^+shift+e', when: 'inFilesPicker && inQuickOpen' },
    { command: '-workbench.action.closeWindow', key: '^+shift+w' },
    { command: '-workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup', key: '^+tab', when: '!activeEditorGroupEmpty' },
    { command: '-workbench.action.quickOpenLeastRecentlyUsedEditorInGroup', key: '^+shift+tab', when: '!activeEditorGroupEmpty' },
    { command: '-workbench.action.quickOpenNavigateNextInViewPicker', key: '^+q', when: 'inQuickOpen && inViewsPicker' },
    { command: '-workbench.action.quickOpenView', key: '^+q' },
    { command: '-workbench.action.quickOpenNavigatePreviousInViewPicker', key: '^+shift+q', when: 'inQuickOpen && inViewsPicker' },
    { command: '-editor.action.marker.nextInFiles', key: 'f8', when: 'editorFocus' },
    { command: '-editor.action.marker.prevInFiles', key: 'shift+f8', when: 'editorFocus' },
    { command: '-breadcrumbs.focusAndSelect', key: '^+shift+oem_period', when: 'breadcrumbsPossible && breadcrumbsVisible' },
    { command: '-breadcrumbs.focus', key: '^+shift+oem_1', when: 'breadcrumbsPossible && breadcrumbsVisible' },
    { command: '-breadcrumbs.focusNext', key: '^+right', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.focusNext', key: 'right', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.focusNextWithPicker', key: '^+right', when: 'breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus' },
    { command: '-breadcrumbs.focusPrevious', key: '^+left', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.focusPrevious', key: 'left', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.focusPreviousWithPicker', key: '^+left', when: 'breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus' },
    { command: '-breadcrumbs.revealFocused', key: '^+enter', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.revealFocused', key: 'space', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.revealFocusedFromTreeAside', key: '^+enter', when: 'breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus' },
    { command: '-breadcrumbs.selectEditor', key: 'escape', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.selectFocused', key: 'down', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-breadcrumbs.selectFocused', key: 'enter', when: 'breadcrumbsActive && breadcrumbsVisible' },
    { command: '-references-view.findReferences', key: 'shift+alt+f12', when: 'editorHasReferenceProvider' },
    { command: '-workbench.action.openRecent', key: '^+r' },
    { command: '-editor.action.goToImplementation', key: '^+f12', when: 'editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor' },
    { command: '-editor.action.autoFix', key: 'shift+alt+oem_period', when: 'textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)quickfix\\b/' },
    { command: '-editor.action.accessibleViewGoToSymbol', key: '^+shift+oem_period', when: 'accessibilityHelpIsShown && accessibleViewGoToSymbolSupported || accessibleViewGoToSymbolSupported && accessibleViewIsShown' },
    { command: '-editor.action.inPlaceReplace.down', key: '^+shift+oem_period', when: 'editorTextFocus && !editorReadonly' },
    { command: '-editor.action.clipboardPasteAction', key: '^+v' },
    {
        command: '-workbench.action.terminal.focus',
        key: '^+down',
        when: "accessibilityModeEnabled && accessibleViewOnLastLine && terminalHasBeenCreated && accessibleViewCurrentProviderId == 'terminal' || accessibilityModeEnabled && accessibleViewOnLastLine && terminalProcessSupported && accessibleViewCurrentProviderId == 'terminal'",
    },
    { command: '-workbench.action.showAllSymbols', key: '^+t' },
    { command: '-workbench.action.terminal.toggleTerminal', key: '^+oem_3', when: 'terminal.active' },
    { command: '-workbench.action.terminal.new', key: '^+shift+oem_3', when: 'terminalProcessSupported || terminalWebExtensionContributedProfile' },
    {
        command: '-workbench.action.terminal.runRecentCommand',
        key: '^+r',
        when: "accessibilityModeEnabled && terminalFocus && terminalHasBeenCreated || accessibilityModeEnabled && terminalFocus && terminalProcessSupported || accessibilityModeEnabled && accessibleViewIsShown && terminalHasBeenCreated && accessibleViewCurrentProviderId == 'terminal' || accessibilityModeEnabled && accessibleViewIsShown && terminalProcessSupported && accessibleViewCurrentProviderId == 'terminal'",
    },
    { command: '-workbench.action.quickOpenNavigateNextInRecentFilesPicker', key: '^+r', when: 'inQuickOpen && inRecentFilesPicker' },
    { command: '-python.refreshTensorBoard', key: '^+r', when: 'python.hasActiveTensorBoardSession' },
    { command: '-workbench.action.gotoLine', key: '^+g' },
    { command: '-editor.action.showHover', key: '^+k ^+i', when: 'editorTextFocus' },
    { command: '-editor.action.selectAll', key: '^+a' },
    { command: '-notification.acceptPrimaryAction', key: '^+shift+a', when: 'notificationFocus || notificationToastsVisible' },
    { command: '-workbench.action.terminal.openNativeConsole', key: '^+shift+c', when: '!terminalFocus' },
    { command: '-workbench.action.terminal.openDetectedLink', key: '^+shift+g', when: "accessibleViewIsShown && terminalHasBeenCreated && accessibleViewCurrentProviderId == 'terminal'" },
    { command: '-workbench.view.extension.thunder-client', key: '^+shift+r' },
    { command: '-editor.action.refactor', key: '^+shift+r', when: 'editorHasCodeActionsProvider && textInputFocus && !editorReadonly' },
    { command: '-rerunSearchEditorSearch', key: '^+shift+r', when: 'inSearchEditor' },
    { command: '-workbench.action.togglePanel', key: '^+j' },
    { command: '-workbench.action.splitEditor', key: '^+oem_5' },
    { command: '-relative-goto.goto', key: 'alt+g' },
    { command: '-workbench.action.openGlobalKeybindings', key: '^+k ^+s' },
    { command: '-cody.command.edit-code', key: '^+k', when: 'cody.activated && config.cody.internal.unstable && !editorReadonly' },
    { command: '-workbench.action.editor.changeLanguageMode', key: '^+k m', when: '!notebookEditorFocused' },
    { command: '-workbench.action.addComment', key: '^+k ^+alt+c' },
    {
        command: '-editor.action.nextCommentingRange',
        key: '^+k ^+alt+down',
        when: "accessibilityModeEnabled && commentFocused || accessibilityModeEnabled && editorFocus || accessibilityHelpIsShown && accessibilityModeEnabled && accessibleViewCurrentProviderId == 'comments'",
    },
    {
        command: '-editor.action.previousCommentingRange',
        key: '^+k ^+alt+up',
        when: "accessibilityModeEnabled && commentFocused || accessibilityModeEnabled && editorFocus || accessibilityHelpIsShown && accessibilityModeEnabled && accessibleViewCurrentProviderId == 'comments'",
    },
    { command: '-editor.createFoldingRangeFromSelection', key: '^+k ^+oem_comma', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.debug.action.showDebugHover', key: '^+k ^+i', when: 'editorTextFocus && inDebugMode' },
    { command: '-editor.action.defineKeybinding', key: '^+k ^+k', when: "resource == 'vscode-userdata:/c%3A/Users/Econn/AppData/Roaming/Code/User/keybindings.json'" },
    { command: '-workbench.files.action.focusOpenEditorsView', key: '^+k e', when: 'workbench.explorer.openEditorsView.active' },
    { command: '-workbench.files.action.compareWithClipboard', key: '^+k c' },
    { command: '-workbench.files.action.compareWithSaved', key: '^+k d' },
    { command: '-copyRelativeFilePath', key: '^+k ^+shift+c', when: '!editorFocus' },
    { command: '-copyRelativeFilePath', key: '^+k ^+shift+c', when: 'editorFocus' },
    { command: '-workbench.action.files.showOpenedFileInNewWindow', key: '^+k o', when: 'emptyWorkspaceSupport' },
    { command: '-workbench.action.files.openFolder', key: '^+k ^+o', when: 'openFolderWorkspaceSupport' },
    { command: '-workbench.action.showAllEditors', key: '^+k ^+p' },
    { command: '-editor.foldAll', key: '^+k ^+0', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldAllBlockComments', key: '^+k ^+oem_2', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldAllExcept', key: '^+k ^+oem_minus', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldAllMarkerRegions', key: '^+k ^+8', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel1', key: '^+k ^+1', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel2', key: '^+k ^+2', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel3', key: '^+k ^+3', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel4', key: '^+k ^+4', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel5', key: '^+k ^+5', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel6', key: '^+k ^+6', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldLevel7', key: '^+k ^+7', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.foldRecursively', key: '^+k ^+oem_4', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.action.formatSelection', key: '^+k ^+f', when: 'editorHasDocumentSelectionFormattingProvider && editorTextFocus && !editorReadonly' },
    { command: '-git.revertSelectedRanges', key: '^+k ^+r', when: 'isInDiffEditor && !operationInProgress' },
    { command: '-git.stageSelectedRanges', key: '^+k ^+alt+s', when: 'isInDiffEditor && !operationInProgress' },
    { command: '-git.unstageSelectedRanges', key: '^+k ^+n', when: 'isInDiffEditor && !operationInProgress' },
    { command: '-workbench.action.navigateToLastEditLocation', key: '^+k ^+q' },
    { command: '-workbench.action.keybindingsReference', key: '^+k ^+r' },
    { command: '-inlineChat.start', key: '^+k i', when: 'editorFocus && inlineChatHasProvider && !editorReadonly' },
    { command: '-java.view.package.copyRelativeFilePath', key: '^+k ^+shift+c', when: "focusedView == 'javaProjectExplorer' && java:serverMode == 'Standard'" },
    { command: '-markdown.showPreviewToSide', key: '^+k v', when: "!notebookEditorFocused && editorLangId == 'markdown'" },
    { command: '-editor.action.moveSelectionToNextFindMatch', key: '^+k ^+d', when: 'editorFocus' },
    { command: '-notebook.cell.collapseCellInput', key: '^+k ^+c', when: 'notebookCellListFocused && !inputFocus && !notebookCellInputIsCollapsed' },
    { command: '-notebook.cell.collapseCellOutput', key: '^+k t', when: 'notebookCellHasOutputs && notebookCellListFocused && !inputFocus && !notebookCellOutputIsCollapsed' },
    { command: '-notebook.cell.expandCellInput', key: '^+k ^+c', when: 'notebookCellInputIsCollapsed && notebookCellListFocused' },
    { command: '-notebook.cell.expandCellOutput', key: '^+k t', when: 'notebookCellListFocused && notebookCellOutputIsCollapsed' },
    { command: '-notebook.cell.split', key: '^+k ^+shift+oem_5', when: 'editorTextFocus && notebookCellEditable && notebookEditable && notebookEditorFocused' },
    { command: '-notebook.cell.toggleOutputScrolling', key: '^+k y', when: 'notebookCellHasOutputs && notebookCellListFocused && !inputFocus' },
    { command: '-notifications.showList', key: '^+k ^+shift+n' },
    { command: '-editor.action.revealDefinitionAside', key: '^+k f12', when: 'editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor' },
    { command: '-editor.action.revealDefinitionAside', key: '^+k ^+f12', when: 'editorHasDefinitionProvider && editorTextFocus && isWeb && !isInEmbeddedEditor' },
    { command: '-workbench.action.selectTheme', key: '^+k ^+t' },
    { command: '-editor.action.removeCommentLine', key: '^+k ^+u', when: 'editorTextFocus && !editorReadonly' },
    { command: '-editor.removeManualFoldingRanges', key: '^+k ^+oem_period', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.action.selectFromAnchorToCursor', key: '^+k ^+k', when: 'editorTextFocus && selectionAnchorSet' },
    { command: '-editor.action.setSelectionAnchor', key: '^+k ^+b', when: 'editorTextFocus' },
    {
        command: '-workbench.action.terminal.focusHover',
        key: '^+k ^+i',
        when: 'terminalFocus && terminalHasBeenCreated || terminalFocus && terminalIsOpen || terminalFocus && terminalProcessSupported || terminalHasBeenCreated && terminalTabsFocus || terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus',
    },
    { command: '-editor.toggleFold', key: '^+k ^+l', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.action.trimTrailingWhitespace', key: '^+k ^+x', when: 'editorTextFocus && !editorReadonly' },
    { command: '-editor.unfoldAll', key: '^+k ^+j', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.unfoldAllExcept', key: '^+k ^+oem_plus', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.unfoldAllMarkerRegions', key: '^+k ^+9', when: 'editorTextFocus && foldingEnabled' },
    { command: '-editor.unfoldRecursively', key: '^+k ^+oem_6', when: 'editorTextFocus && foldingEnabled' },
    { command: '-workbench.action.closeAllGroups', key: '^+k ^+shift+w' },
    { command: '-workbench.action.closeAllEditors', key: '^+k ^+w' },
    { command: '-workbench.action.closeEditorsInGroup', key: '^+k w' },
    { command: '-workbench.action.closeUnmodifiedEditors', key: '^+k u' },
    { command: '-workbench.action.focusAboveGroup', key: '^+k ^+up' },
    { command: '-workbench.action.focusBelowGroup', key: '^+k ^+down' },
    { command: '-workbench.action.focusLeftGroup', key: '^+k ^+left' },
    { command: '-workbench.action.focusRightGroup', key: '^+k ^+right' },
    { command: '-workbench.action.joinEditorInGroup', key: '^+k ^+shift+oem_5', when: 'sideBySideEditorActive' },
    { command: '-workbench.action.keepEditor', key: '^+k enter' },
    { command: '-workbench.action.moveActiveEditorGroupDown', key: '^+k down' },
    { command: '-workbench.action.moveActiveEditorGroupLeft', key: '^+k left' },
    { command: '-workbench.action.moveActiveEditorGroupRight', key: '^+k right' },
    { command: '-workbench.action.moveActiveEditorGroupUp', key: '^+k up' },
    { command: '-workbench.action.pinEditor', key: '^+k shift+enter', when: '!activeEditorIsPinned' },
    { command: '-workbench.action.splitEditorDown', key: '^+k ^+oem_5' },
    { command: '-workbench.action.splitEditorInGroup', key: '^+k ^+shift+oem_5', when: 'activeEditorCanSplitInGroup' },
    { command: '-workbench.action.splitEditorLeft', key: '^+k ^+oem_5' },
    { command: '-workbench.action.splitEditorOrthogonal', key: '^+k ^+oem_5' },
    { command: '-workbench.action.splitEditorRight', key: '^+k ^+oem_5' },
    { command: '-workbench.action.splitEditorUp', key: '^+k ^+oem_5' },
    { command: '-workbench.action.toggleMaximizeEditorGroup', key: '^+k ^+m', when: 'editorPartMaximizedEditorGroup || editorPartMultipleEditorGroups' },
    { command: '-workbench.action.unpinEditor', key: '^+k shift+enter', when: 'activeEditorIsPinned' },
    { command: '-workbench.action.closeFolder', key: '^+k f', when: "emptyWorkspaceSupport && workbenchState != 'empty'" },
    { command: '-keybindings.editor.addKeybinding', key: '^+k ^+a', when: 'inKeybindings && keybindingFocus' },
    { command: '-keybindings.editor.defineWhenExpression', key: '^+k ^+e', when: 'inKeybindings && keybindingFocus' },
    { command: '-markdown.extension.closePreview', key: '^+k v', when: "activeWebviewPanelId == 'markdown.preview'" },
    { command: '-togglePeekWidgetFocus', key: '^+k f2', when: 'inReferenceSearchEditor || referenceSearchVisible' },
    { command: '-views.moveViewDown', key: '^+k down', when: "focusedView != ''" },
    { command: '-views.moveViewLeft', key: '^+k left', when: "focusedView != ''" },
    { command: '-views.moveViewRight', key: '^+k right', when: "focusedView != ''" },
    { command: '-views.moveViewUp', key: '^+k up', when: "focusedView != ''" },
    { command: '-workbench.action.compareEditor.openSide', key: '^+k shift+o', when: 'inDiffEditor' },
    { command: '-workbench.action.files.copyPathOfActiveFile', key: '^+k p' },
    { command: '-workbench.action.files.openLocalFolder', key: '^+k ^+o', when: 'remoteFileDialogVisible' },
    { command: '-workbench.action.files.revealActiveFileInWindows', key: '^+k r' },
    { command: '-workbench.action.showTreeHover', key: '^+k ^+i', when: 'customTreeView && listFocus && !inputFocus' },
    { command: '-editor.action.insertCursorAbove', key: '^+alt+up', when: 'editorTextFocus' },
    { command: '-editor.action.insertCursorBelow', key: '^+alt+down', when: 'editorTextFocus' },
    { command: '-workbench.action.terminal.paste', key: '^+v', when: 'terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported' },
    { command: '-workbench.action.terminal.paste', key: '^+shift+v', when: 'terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported' },
    { command: '-breadcrumbs.toggleToOn', key: '^+shift+oem_period', when: '!config.breadcrumbs.enabled' },
    { command: '-workbench.action.showCommands', key: 'f1' },
    //
    //
    //                Additions
    //
    //
    { command: 'editor.action.smartSelect.grow', key: '^+a', when: 'editorTextFocus' },
    { command: 'editor.action.selectAll', key: '^+a', when: 'inputFocus&&!editorTextFocus' },
    { command: 'editor.action.selectAll', key: '^+shift+a', when: 'editorTextFocus' },
    { command: 'workbench.action.quickOpen', key: '^+r', args: 'task ', when: 'editorTextFocus&&!isDevelopment' },
    { command: 'workbench.action.quickOpen', key: '^+g', args: '@: ', when: 'editorTextFocus' },
    { command: 'workbench.action.quickOpen', key: '^+;', args: ': ', when: 'editorTextFocus' },
    { command: 'editor.action.insertSnippet', key: '^+i' },
    { command: 'editor.action.selectHighlights', key: '^+shift+d', when: 'editorFocus' },
    { command: 'workbench.view.explorer', key: '^+1', when: 'viewContainer.workbench.view.explorer.enabled' },
    { command: 'workbench.view.debug', key: '^+3' },
    { command: 'workbench.action.debug.restart', key: 'f5', when: "inDebugMode && debugState == 'running'" },
    { command: 'workbench.action.previousEditorInGroup', key: 'alt+left' },
    { command: 'workbench.action.nextEditorInGroup', key: 'alt+right' },
    { command: 'editor.action.jumpToBracket', key: '^+b', when: 'editorTextFocus && editorLangId!=markdown' },
    { command: 'workbench.action.toggleSidebarVisibility', key: '^+oem_8' },
    { command: 'editor.action.organizeImports', key: '^+o', when: 'textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)source\\.organizeImports\\b/' },
    { command: 'saveAll', key: '^+shift+s' },
    { command: 'workbench.action.files.saveWithoutFormatting', key: 'alt+s' },
    { command: 'workbench.action.toggleZenMode', key: 'f11' },
    { command: 'workbench.action.openSettingsJson', key: '^+shift+e' },
    { command: 'notebook.execute', key: 'f5', when: 'notebookEditorFocused' },
    { command: 'workbench.action.closeOtherEditors', key: '^+shift+w' },
    { command: 'workbench.action.quickOpenNavigateNextInViewPicker', key: '^+tab', when: 'inQuickOpen && inViewsPicker' },
    { command: 'workbench.action.quickOpenView', key: '^+tab', when: '!inQuickOpen' },
    { command: 'workbench.action.focusActiveEditorGroup', key: '^+e' },
    { command: 'workbench.action.quickOpenNavigatePreviousInViewPicker', key: '^+shift+tab', when: 'inQuickOpen && inViewsPicker' },
    { command: 'editor.action.marker.nextInFiles', key: '^+e', when: 'editorFocus' },
    { command: 'editor.action.marker.prevInFiles', key: '^+shift+e', when: 'editorFocus' },
    { command: 'editor.action.goToImplementation', key: 'alt+enter', when: 'editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor' },
    { command: 'editor.action.autoFix', key: '^+shift+oem_period', when: 'textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)quickfix\\b/' },
    { command: 'editor.action.clipboardPasteAction', key: '^+v', when: '!terminalFocus' },
    { command: 'references-view.findReferences', key: 'f4' },
    { command: 'references-view.findImplementations', key: 'f3' },
    { command: 'editor.action.fixAll', key: '^+q' },
    { command: 'workbench.action.terminal.killEditor', key: '^+w', when: 'terminalFocus' },
    { command: 'editor.action.showHover', key: 'shift+space', when: 'editorTextFocus' },
    { command: 'workbench.action.terminal.toggleTerminal', key: '^+oem_5' },
    { command: 'workbench.action.terminal.clear', key: '^+k' },
    { command: 'editor.action.insertCursorAbove', key: 'shift+alt+up', when: 'editorTextFocus' },
    { command: 'editor.action.insertCursorBelow', key: 'shift+alt+down', when: 'editorTextFocus' },
    { command: 'workbench.action.createTerminalEditor', key: '^+t' },
    { command: 'workbench.action.terminal.paste', key: '^+v', when: 'terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported' },
    { command: 'editor.action.goToTypeDefinition', key: 'f1' },
    { command: 'workbench.action.terminal.runRecentCommand', key: '^+r', when: 'terminalFocus && terminalHasBeenCreated && !accessibilityModeEnabled || terminalFocus && terminalProcessSupported && !accessibilityModeEnabled' },
    {
        command: 'runCommands',
        key: '^+shift+g',
        args: {
            commands: [
                'workbench.action.createTerminalEditor',
                {
                    command: 'workbench.action.terminal.sendSequence',
                    args: {
                        text: 'lazygit\r',
                    },
                },
            ],
        },
    },
    {
        command: 'toggle',
        key: '^+shift+i',
        when: 'editorTextFocus',
        args: {
            id: 'minimap',
            value: [
                {
                    'editor.inlayHints.enabled': 'onUnlessPressed',
                },
                {
                    'editor.inlayHints.enabled': 'offUnlessPressed',
                },
            ],
        },
    },
    {
        command: 'toggle',
        key: '^+shift+l',
        when: 'editorTextFocus',
        args: {
            id: 'minimap',
            value: [
                {
                    'editor.lineNumbers': 'off',
                },
                {
                    'editor.lineNumbers': 'on',
                },
            ],
        },
    },
    { when: 'terminalFocus', key: '^+left', command: 'workbench.action.terminal.sendSequence', args: { text: '\u001b[1;5D' } },
    { when: 'terminalFocus', key: '^+right', command: 'workbench.action.terminal.sendSequence', args: { text: '\u001b[1;5C' } },
    { when: '!terminalTextSelectedInFocused && terminalFocus', key: '^+c', command: 'workbench.action.terminal.sendSequence', args: { text: '\u0003' } },
]

export default custom
